In [8]:
#concepts of tensorflow 
import tensorflow as tf

In [11]:
print(tf.__version__)

2.16.1


In [13]:
#create tensors with tf.constant
scalar = tf.constant(7)
scalar 

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [15]:
#check number of ndimentions 
scalar.ndim

0

In [17]:
#create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [18]:
vector.ndim

1

In [23]:
matrix = tf.constant([[10,7],[2,17]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2, 17]])>

In [24]:
matrix.ndim

2

In [27]:
#create another matrix 
matrix_1 = tf.constant([[10.,7.],[3.,2.],[8.,9.]], dtype = tf.float16)
matrix_1

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [28]:
matrix_1.ndim

2

In [34]:
#create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                       [[7,8,9]
                       ,[10,11,12]],
                     [[13,14,15],
                     [16,17,18]]])
tensor 


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [35]:
tensor.ndimff

3

In [36]:
tf.Variable

tensorflow.python.ops.variables.Variable